feat: determine if the host has a gpu
open-v2x/hippocampus pull request #103
Opened 2022-11-14 05:23 UTC by srx0914

2022-11-14 08:10 UTC, wu-wenxiang requested changes
```python
def Receive():
    print("start Reveive ...")
    while True:
        cap = cv2.VideoCapture(os.getenv("rtsp"))
        cap.set(cv2.CAP_PROP_BUFFERSIZE, 2)
        while cap.isOpened():
            _, frame = cap.read()
            deq.append(frame)
        print('deq is empty, retry')
        time.sleep(1)
```

2022-11-14 08:10 UTC, wu-wenxiang commented on main.py
> +                pipe.stdin.write(im.tobytes())
```python
if deq:
    ...
else:
    time.sleep(1)
```

2022-11-14 08:10 UTC, wu-wenxiang commented on main.py
> +    else:
```python
if not torch.cuda.is_available():
    ...
else:  # 去掉
```

2022-11-14 08:10 UTC, wu-wenxiang commented on main.py
> +            if deq:
if deq 后面应该有对应的 else，然后 sleep(1)

2022-11-14 09:21 UTC, wu-wenxiang requested changes

2022-11-14 09:21 UTC, wu-wenxiang commented on main.py
> +        print("deq is empty, retry, time:{}".format(other_StyleTime))
太复杂了，这样吧

```python
print("[{} UTC] deq is empty, retry...".format(datetime.datetime.utcnow()))
```

2022-11-14 09:56 UTC, wu-wenxiang requested changes

2022-11-14 09:56 UTC, wu-wenxiang commented on main.py
> +        print("[{} UTC] deq is empty, retry...".format(datetime.datetime.utcnow()))
print("[{} UTC] rtsp stream is closed, retry...".format(datetime.datetime.utcnow()))

2022-11-14 09:56 UTC, wu-wenxiang commented on main.py
> +                time.sleep(1)
print("[{} UTC] deq is empty, retry...".format(datetime.datetime.utcnow()))

2022-11-14 09:56 UTC, wu-wenxiang commented on main.py
> +            time.sleep(1)
print("[{} UTC] deq is empty, retry...".format(datetime.datetime.utcnow()))

2022-11-15 01:38 UTC, FrankGTY approved these changes

2022-11-15 01:46 UTC, wu-wenxiang approved these changes

2022-11-15 01:46 UTC, merged