docs: add development documentation
open-v2x/hippocampus pull request #32
Opened 2022-10-24 08:55 UTC by srx0914

2022-10-24 09:32 UTC, wu-wenxiang requested changes

2022-10-24 09:32 UTC, wu-wenxiang commented on docs/development_doc.md
> +1. 阿里云 T4 机器开启，11.6 元/小时，Ubuntu 22.04(20.04 后面的步骤不适用)，4Core 16G 40G
T4 GPU 服务器，Ubuntu 22.04(20.04 不适用)，4Core 16G 40G

2022-10-24 09:32 UTC, wu-wenxiang commented on docs/development_doc.md
> +2. ansible-playbook -i inventory/lab-c2009.ini playbooks/cloudlab-init-with-rdp.yaml 初始化 SSH 等
去掉

2022-10-24 09:32 UTC, wu-wenxiang commented on docs/development_doc.md
> +```python
bash

2022-10-24 09:32 UTC, wu-wenxiang commented on docs/development_doc.md
> +```python
json

2022-10-24 09:32 UTC, wu-wenxiang commented on docs/development_doc.md
> +```python
bash

2022-10-24 09:32 UTC, wu-wenxiang commented on docs/development_doc.md
> +3.4. 启动docker
盘古之白

2022-10-24 09:32 UTC, wu-wenxiang commented on docs/development_doc.md
> +```python
bash

2022-10-24 09:32 UTC, wu-wenxiang commented on docs/development_doc.md
> +sudo apt install software-properties-common -y
bash

2022-10-24 09:32 UTC, wu-wenxiang commented on docs/development_doc.md
> +2. 参考 https://blog.51cto.com/ganzy/5636414，现在 hippocampus 用 pytorch < 1.10 版本，python 必须 < 3.10
<https://blog.51cto.com/ganzy/5636414>

2022-10-24 09:32 UTC, wu-wenxiang commented on docs/development_doc.md
> +参考 https://zhc3o5gmf9.feishu.cn/docx/doxcnNrfygF4WnWVYhCygILsuqd
<https://...>

2022-10-24 09:32 UTC, wu-wenxiang commented on docs/development_doc.md
> +```
bash

2022-10-24 09:32 UTC, wu-wenxiang commented on docs/development_doc.md
> +vlc 可以访问 rtmp://localhost:1935/live/result
链接，加 <> 符号

2022-10-25 02:00 UTC, srx0914 commented on docs/development_doc.md
> +2. ansible-playbook -i inventory/lab-c2009.ini playbooks/cloudlab-init-with-rdp.yaml 初始化 SSH 等
已经去掉

2022-10-25 02:03 UTC, srx0914 commented on docs/development_doc.md
> +```python
已经修改

2022-10-25 02:04 UTC, srx0914 commented on docs/development_doc.md
> +```python
已经修改

2022-10-25 02:04 UTC, srx0914 commented on docs/development_doc.md
> +```python
已经修改

2022-10-25 02:06 UTC, srx0914 commented on docs/development_doc.md
> +sudo apt install software-properties-common -y
已经修改

2022-10-25 03:16 UTC, FrankGTY approved these changes

2022-10-25 03:31 UTC, merged

2022-10-25 04:37 UTC, wu-wenxiang commented on docs/development_doc.md
> +```bash
console

2022-10-25 04:37 UTC, wu-wenxiang commented on docs/development_doc.md
> +```bash
console